# Docker Compose specific configureation file for PushmiPullyu.
# Based on the pushmi_pullyu/example/pushmi_pullyu.yml

# Options here can still be overridden by cmd line args.

# Pass this file at config/pushmi_pullyu.yml and PushmiPullyu will
# pick it up automatically. Or pass this file into pushmi_pullyu on command line
# via `pushmi_pullyu -C path/to/pushmi_pullyu.yml`

# PushmiPullyu will run this file through ERB when reading it so you can
# even put in dynamic logic, like consuming ENV Variables.

debug: true 
logfile: log/pushmi_pullyu.log
monitor: true 
piddir: tmp/pids
process_name: pushmi_pullyu
queue_name: dev:pmpy_queue
minimum_age: 0
rollbar_token: 'abc123xyz'

redis:
  host: <%= ENV['REDIS_HOST'] %> 
  port: 6379

solr:
  url: http://<%= ENV['SOLR_HOST'] %>:8983/solr/development

fedora:
  url: http://<%= ENV['FEDORA_HOST'] %>:8983/rest
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  base_path: /dev

swift:
  auth_version: 2.0
  tenant: Millennium Falcon
  username: han
  password: YT-1300
  endpoint: <%= ENV['SWIFT_ENDPOINT'] %>
  temp_url_key: 492727ZED
